# This file is going to be fill when I get a sponsor. Email me at zerpaanthony.wx@breadriuss.com

github: anthonycursewl
patreon:
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt:
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom:
