import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, width: '100%' },
    input: {
      borderWidth: 1,
      borderColor: '#E5E5E5',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: '#fff',
    },
    selectInput: {
      backgroundColor: '#F5F5F5',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: '#E5E5E5',
    },
    inputText: {
      color: '#6B7280',
      fontSize: 16,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: '#fff',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 10,
    },
    modalHandle: {
      width: 40,
      height: 4,
      backgroundColor: '#E5E5E5',
      borderRadius: 2,
      alignSelf: 'center',
      marginTop: 10,
      marginBottom: 15,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E5E5',
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '600',
    },
    closeButton: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#6B7280',
    },
    categoryItem: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E5E5',
    },
    providerItem: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E5E5',
    },
    categoryName: {
      fontSize: 16,
      color: '#1F2937',
    },
    providerName: {
      fontSize: 16,
      color: '#1F2937',
    },
    modalOption: {
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E5E5',
    },
    modalOptionText: {
      fontSize: 16,
      color: '#1F2937',
    },
    formContainer: { width: '100%', marginTop: 15, gap: 20 },
    fieldGroup: { width: '100%', gap: 8 },
    label: { fontSize: 18 },
    barcodeContainer: { flexDirection: 'row', alignItems: 'center', width: '100%' },
    scanButton: { backgroundColor: '#2196F3', padding: 10, borderRadius: 5, marginLeft: 8, justifyContent: 'center', alignItems: 'center' },
    generateButton: { backgroundColor: '#4CAF50' },
    sectionContainer: { width: '100%', gap: 18, marginTop: 10 },
    sectionTitle: { fontSize: 20, fontWeight: 'bold' },
    switchContainer: { width: '100%', gap: 8, flexDirection: 'row', alignItems: 'center' },
    submitButtonContainer: { width: '100%', marginTop: 30, marginBottom: 20 },
    scannerContainer: { flex: 1, backgroundColor: 'black' },
    pickerContainer: {
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 8,
      marginBottom: 16,
      overflow: 'hidden',
    },
    picker: {
      width: '100%',
      height: 50,
      color: '#333',
    },
    cancelButtonContainer: { position: 'absolute', bottom: 40, left: 20, right: 20 },
    cancelScanButton: { backgroundColor: 'rgba(244, 67, 54, 0.8)', padding: 15, borderRadius: 8, alignItems: 'center' },
    cancelScanText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
    centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    centerContainerWithPadding: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
    permissionText: { textAlign: 'center', marginBottom: 20 },
    overlay: { ...StyleSheet.absoluteFillObject, flex: 1 },
    mask: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.6)' },
    centerRow: { flexDirection: 'row', height: 200 },
    scanWindow: { width: '75%', height: '100%', overflow: 'hidden' },
    corner: { position: 'absolute', width: 30, height: 30, borderColor: '#fff' },
    topLeft: { top: 0, left: 0, borderTopWidth: 4, borderLeftWidth: 4 },
    topRight: { top: 0, right: 0, borderTopWidth: 4, borderRightWidth: 4 },
    bottomLeft: { bottom: 0, left: 0, borderBottomWidth: 4, borderLeftWidth: 4 },
    bottomRight: { bottom: 0, right: 0, borderBottomWidth: 4, borderRightWidth: 4 },
    scanLine: { width: '100%', height: 2, backgroundColor: '#ff0000', shadowColor: '#ff0000', shadowOpacity: 0.8, shadowRadius: 5, elevation: 10 },
    scanHelpText: { color: 'white', fontSize: 16, marginTop: -50, backgroundColor: 'rgba(0,0,0,0.5)', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 5 },
  });
